In [62]:
from PIL import Image
import numpy as np

In [72]:



print("(test.jpg) File : ")
name = input()
if(name == ""):
    name = "test.jpg"
print("")
print("Image = "+str(name))

##
pictur = Image.open(str(name))
width, height = pictur.size
##

print("")
print("(2) Binning Faktor (even subdivide from width and height): ")
faktor = input()
if(faktor == ""):
    faktor = 2

if(width % int(faktor) != 0):
    print("")
    print("Faktor is not an even divisor!!!")
    print("")
    print("Faktor is now [2]")
    faktor = 2

print("")
print("Faktor = "+str(faktor))

print("")
print("Converting ["+str(name)+"] with a faktor of ["+str(faktor)+"]...")

print("")
print("Size: "+str(width)+" x "+str(height))

(test.jpg) File : 

Image = test.jpg

(2) Binning Faktor (even subdivide from width and height): 

Faktor = 2

Converting [test.jpg] with a faktor of [2]...

Size: 16 x 16


In [73]:
tmp_gesR = 0
tmp_gesG = 0
tmp_gesB = 0
tmp_ges = tmp_gesR, tmp_gesG, tmp_gesB
tmp_tmp_gesR = 0
tmp_tmp_gesG = 0
tmp_tmp_gesB = 0

newimgarray = np.zeros((int(height / faktor), int(width / faktor), 3))

In [76]:
print(pictur.getpixel((0,0)))
print(pictur.getpixel((1,0)))
print(pictur.getpixel((0,1)))
print(pictur.getpixel((1,1)))
#select main pixel
for y in range( int(width / faktor) ):

	for x in range( int(height  / faktor) ):

		#get pixel value from 0.0, from 0.+1, from +1.0, from +1.+1
		tmp_tmp_gesR = 0
		tmp_tmp_gesG = 0
		tmp_tmp_gesB = 0

		xtmp,ytmp = x*faktor,y*faktor
		
		for i in range(faktor):
			for j in range(faktor):
				
				tmp_gesR, tmp_gesG, tmp_gesB = pictur.getpixel((xtmp+i,ytmp+j)) 
				tmp_tmp_gesR, tmp_tmp_gesG, tmp_tmp_gesB = tmp_tmp_gesR + tmp_gesR, tmp_tmp_gesG + tmp_gesG, tmp_tmp_gesB + tmp_gesB

		newimgarray[y][x][0] = tmp_tmp_gesR
		newimgarray[y][x][1] = tmp_tmp_gesG
		newimgarray[y][x][2] = tmp_tmp_gesB
##
print(newimgarray)

(1, 1, 1)
(3, 3, 3)
(3, 3, 3)
(4, 4, 4)
[[[ 11.  11.  11.]
  [ 23.  23.  23.]
  [ 33.  33.  33.]
  [ 45.  45.  45.]
  [ 58.  58.  58.]
  [ 74.  74.  74.]
  [ 84.  84.  84.]
  [ 92.  92.  92.]]

 [[ 23.  23.  23.]
  [ 35.  35.  35.]
  [ 45.  45.  45.]
  [ 57.  57.  57.]
  [ 68.  68.  68.]
  [ 82.  82.  82.]
  [ 92.  92.  92.]
  [104. 104. 104.]]

 [[ 33.  33.  33.]
  [ 45.  45.  45.]
  [ 56.  56.  56.]
  [ 68.  68.  68.]
  [ 79.  79.  79.]
  [ 91.  91.  91.]
  [104. 104. 104.]
  [118. 118. 118.]]

 [[ 45.  45.  45.]
  [ 57.  57.  57.]
  [ 68.  68.  68.]
  [ 80.  80.  80.]
  [ 94.  94.  94.]
  [105. 105. 105.]
  [118. 118. 118.]
  [136. 136. 136.]]

 [[ 60.  60.  60.]
  [ 68.  68.  68.]
  [ 79.  79.  79.]
  [ 93.  93.  93.]
  [104. 104. 104.]
  [116. 116. 116.]
  [134. 134. 134.]
  [156. 156. 156.]]

 [[ 70.  70.  70.]
  [ 81.  81.  81.]
  [ 92.  92.  92.]
  [107. 107. 107.]
  [121. 121. 121.]
  [136. 136. 136.]
  [155. 155. 155.]
  [175. 175. 175.]]

 [[ 80.  80.  80.]
  [ 93.  93.  93.

In [75]:
#newimg = Image.fromarray(newimgarray, )
#newimg.save(str(name), "JPEG")

Image.fromarray((newimgarray).astype('uint8'), mode='RGB').save('pic2.png')